call NewCategory('abstract_', 'Abstract');
call NewCategory('abstract_net', 'Abstract Net');
call NewCategory('abstract_nonphoto', 'Abstract Nonphoto');
call NewCategory('abstract_rect', 'Abstract Rectangle');
call NewCategory('abstract_shape', 'Abstract Shape');
call NewCategory('abstract_texture', 'Abstract Texture');
call NewCategory('animal_', 'Animal');
call NewCategory('animal_bird', 'Bird');
call NewCategory('animal_cat', 'Cat');
call NewCategory('animal_dog', 'Dog');
call NewCategory('animal_horse', 'Horse');
call NewCategory('animal_panda', 'Panda');
call NewCategory('building_', 'Building');
call NewCategory('building_arch', 'Building Arch');
call NewCategory('building_brickwall', 'Building Brickwall');
call NewCategory('building_church', 'Church');
call NewCategory('building_corner', 'Building Corner');
call NewCategory('building_doorwindows', 'Building Doors/Windows');
call NewCategory('building_pillar', 'Building Pillar');
call NewCategory('building_stair', 'Building Stair');
call NewCategory('building_street', 'Building Street');
call NewCategory('dark_', 'Dark');
call NewCategory('drink_', 'Drink');
call NewCategory('drink_can', 'Drink Can');
call NewCategory('dark_fire', 'Dark, fire');
call NewCategory('dark_fireworks', 'Fireworks');
call NewCategory('sky_object', 'Sky object');
call NewCategory('food_', 'Food');
call NewCategory('food_bread', 'Bread');
call NewCategory('food_fastfood', 'Fast Food');
call NewCategory('food_grilled', 'Grilled Food');
call NewCategory('food_pizza', 'Pizza');
call NewCategory('indoor_', 'Indoors');
call NewCategory('indoor_churchwindow', 'Indoor Churchwindow');
call NewCategory('indoor_court', 'Courtroom');
call NewCategory('indoor_doorwindows', 'Indoor Doors/Windows');
call NewCategory('indoor_marketstore', 'Market/Store');
call NewCategory('indoor_room', 'Indoor Room');
call NewCategory('indoor_venue', 'Indoor Venue');
call NewCategory('dark_light', 'Dark Light');
call NewCategory('others_', 'Other');
call NewCategory('outdoor_', 'Outdoors');
call NewCategory('outdoor_city', 'Outdoor City');
call NewCategory('outdoor_field', 'Outdoor Field');
call NewCategory('outdoor_grass', 'Outdoor Grass');
call NewCategory('outdoor_house', 'Outdoor House');
call NewCategory('outdoor_mountain', 'Outdoor Mountain');
call NewCategory('outdoor_oceanbeach', 'Outdoor Beach');
call NewCategory('outdoor_playground', 'Outdoor Playground');
call NewCategory('outdoor_railway', 'Outdoor Railway');
call NewCategory('outdoor_road', 'Outdoor Road');
call NewCategory('outdoor_sportsfield', 'Outdoor Sportsfield');
call NewCategory('outdoor_stonerock', 'Outdoor Stone/Rock');
call NewCategory('outdoor_street', 'Outdoor Street');
call NewCategory('outdoor_water', 'Outdoor Water');
call NewCategory('outdoor_waterside', 'Outdoor Waterslide');
call NewCategory('people_', 'People');
call NewCategory('people_baby', 'Baby');
call NewCategory('people_crowd', 'Crowd');
call NewCategory('people_group', 'People Group');
call NewCategory('people_hand', 'People Hand');
call NewCategory('people_many', 'Many People');
call NewCategory('people_portrait', 'People Portrait');
call NewCategory('people_show', 'People Show');
call NewCategory('people_tattoo', 'People Tatto');
call NewCategory('people_young', 'Young People');
call NewCategory('plant_', 'Plants');
call NewCategory('plant_branch', 'Tree Branch');
call NewCategory('plant_flower', 'Flowers');
call NewCategory('plant_leaves', 'Leaves');
call NewCategory('plant_tree', 'Trees');
call NewCategory('object_screen', 'Screen');
call NewCategory('object_sculpture', 'Sculpture');
call NewCategory('sky_cloud', 'Cloud');
call NewCategory('sky_sun', 'Sun');
call NewCategory('people_swimming', 'People Swimming');
call NewCategory('outdoor_pool', 'Outdoor Pool');
call NewCategory('text_', 'Text');
call NewCategory('text_mag', 'Magazine');
call NewCategory('text_map', 'Map');
call NewCategory('text_menu', 'Menu');
call NewCategory('text_sign', 'Sign');
call NewCategory('trans_bicycle', 'Bicycle');
call NewCategory('trans_bus', 'Bus');
call NewCategory('trans_car', 'Car');
call NewCategory('trans_trainstation', 'Trainstation');